### ISSUE TITLE
Incompatibilities with FEniCS 1.6

### ISSUE THREAD

**Issue by ahellander** [ahellander/pyurdme#139] opened 2015-08-22 10:58 UTC
Current code is not compatible with FEniCS 1.6.0
See also: 
https://github.com/Molns/molns/issues/39

**Comment by briandrawert** [comment] 2015-09-02 21:04
Is this a duplicate of #141 and https://github.com/Molns/molns/issues/39? Both are closed.

**Closed** 2015-09-15 19:03 UTC
Labels: bug
